baseURL = "http://kb.sandiegodata.org/"
languageCode = "en-us"
title = "San Diego Data Knowledge Base"
theme = "kube"
publishDir = "../docs"

Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "San Diego Regional Data Library" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "eric@sandiegodata.org"


[[menu.main]]
    name = "Analysis"
    weight = 1
    url = "/analysis/"
#[[menu.main]]
#    name = "Docs"
#    weight = 2
#    url = "/docs/"
#[[menu.main]]
#    name = "Blog"
#    weight = 3
#    url = "/blog/"
#[[menu.main]]
#    name = "About"
#    weight = 4
#    url = "/faq/"
